Allow use array and multi arguments
doctrine/collections pull request #100
Opened 2016-12-13 21:39 UTC by vlastv

2016-12-13 21:42 UTC, lcobucci commented
@vlastv please provide a test case as well. 

BTW why do you need that? Can't you use `...$myArray` on the function call?

2016-12-13 21:49 UTC, vlastv commented
Variable-length arguments implemented in PHP 5.6, library can work with PHP 5.5 based on composer.json.

I use in case:
```php
$restrictions = [];
foreach($filters as $field => $value) {
    $restrictions[] = Criteria::expr()->eq($field, $value);
}

$criteria->andWhere(call_user_func_array([Criteria::expr(), 'andX'], $restrictions]));
```

IMHO, it next variant is more readable:
```php
// loop

$criteria->andWhere(Criteria::expr()->andX($restrictions)));
```

2016-12-13 22:03 UTC, Ocramius commented
@vlastv can be bumped to PHP 5.6 as minimum requirement

2016-12-13 22:07 UTC, vlastv commented
@Ocramius If you change the minimum version then this request can be rejected.

2016-12-14 02:51 UTC, Ocramius commented
@vlastv I'm suggesting to add it to this patch ;-)

2016-12-14 12:53 UTC, Ocramius requested changes

2016-12-14 12:53 UTC, Ocramius commented on lib/Doctrine/Common/Collections/ExpressionBuilder.php
> +        return new CompositeExpression(CompositeExpression::TYPE_AND, is_array($x) ? $x : func_get_args());
This should be changed to just accept `$x`, and the method signature should become `...$x`

2016-12-14 12:53 UTC, Ocramius commented on lib/Doctrine/Common/Collections/ExpressionBuilder.php
> +        return new CompositeExpression(CompositeExpression::TYPE_OR, is_array($x) ? $x : func_get_args());
This should be changed to just accept `$x`, and the method signature should become `...$x`

2016-12-14 12:53 UTC, Ocramius commented on tests/Doctrine/Tests/Common/Collections/ExpressionBuilderTest.php
> +        $expr = $this->builder->andX($x);
This seems invalid to me

2016-12-14 12:53 UTC, Ocramius commented on tests/Doctrine/Tests/Common/Collections/ExpressionBuilderTest.php
> +        $expr = $this->builder->orX($x);
This seems invalid to me

2016-12-14 13:48 UTC, lcobucci commented on lib/Doctrine/Common/Collections/ExpressionBuilder.php
> +    public function andX(...$x)
@Ocramius should we use `Expression ...$x` as well (and drop the `mixed`)?

2016-12-14 13:56 UTC, lcobucci commented on lib/Doctrine/Common/Collections/ExpressionBuilder.php
> +    public function andX(...$x)
HHVM pffff 😜

2016-12-14 13:59 UTC, lcobucci commented on lib/Doctrine/Common/Collections/ExpressionBuilder.php
> +    public function andX(...$x)
@stof are you sure about strings? https://github.com/doctrine/collections/blob/0b0b54166319e02f50f996f8d966aed368a78bfe/lib/Doctrine/Common/Collections/Expr/CompositeExpression.php#L49 seems to say something different...

2016-12-14 13:59 UTC, stof commented
The current state of the PR does not change the API at all. It still does not allow to pass a single array instead of variadic arguments. So it has no benefit for people using Doctrine (it does not allow to do what the description says).

@vlastv if your own code runs on PHP 5.6+, you can avoid ``call_user_func_array`` today without any change in Doctrine:

```php
// loop

$criteria->andWhere(Criteria::expr()->andX(...$restrictions)));
```

2016-12-14 13:59 UTC, vlastv commented on lib/Doctrine/Common/Collections/ExpressionBuilder.php
> +    public function andX(...$x)
@stof strings not allowed [here](https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/Expr/CompositeExpression.php#L57)

2016-12-14 14:00 UTC, stof commented on lib/Doctrine/Common/Collections/ExpressionBuilder.php
> +    public function andX(...$x)
sorry, I confused the Criteria system in doctrine/collection with the expression builder of the QueryBuilder. Forget my comment.

2016-12-14 14:01 UTC, stof commented
So the *only* thing achieved by your PR so far is breaking support for HHVM, without any benefit for users of the API...

2016-12-26 12:14 UTC, vlastv commented
I close this PR?

2017-05-20 14:49 UTC, lcobucci commented
Now that we dropped HHVM support we can rebase this branch and be more strict on the typehint...

2019-03-24 17:54 UTC, Ocramius commented
This can only target 2.x, sadly. See https://3v4l.org/QIi9Y - it is a BC break due to the `ExpressionBuilder` being an open class.

2021-01-19 07:24 UTC, closed without merging