Case insensitive like
doctrine/collections pull request #123
Opened 2017-07-11 15:11 UTC by okoehler

This PR adds Comparison::CONTAINS_CI to create a case insensitive like. 

Depends on doctrine [PR#6547](https://github.com/doctrine/doctrine2/pull/6547)

2017-07-12 06:13 UTC, Ocramius requested changes

2017-07-12 06:13 UTC, Ocramius commented on lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
> +            case Comparison::CONTAINS_CI:
`strpos` is case-sensitive, so this block is invalid

2017-07-15 02:16 UTC, Majkl578 commented on lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
> +                    return false !== strpos(mb_strtolower(ClosureExpressionVisitor::getObjectFieldValue($object, $field)), mb_strtolower($value));
Hmm, although it's correct, using mb_strtolower introduces dependency on ext-mbstring, which is not bundled in PHP. It's not hard dependency (required only when ICONTAINS is used), but it should probably be added to _suggest_ section in the composer.json.

2017-07-18 07:47 UTC, okoehler commented on lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
> +                    return false !== strpos(mb_strtolower(ClosureExpressionVisitor::getObjectFieldValue($object, $field)), mb_strtolower($value));
@Majkl578 Done (PR updated)

2017-07-31 15:33 UTC, lcobucci commented on lib/Doctrine/Common/Collections/Expr/ClosureExpressionVisitor.php
> +                    return false !== strpos(mb_strtolower(ClosureExpressionVisitor::getObjectFieldValue($object, $field)), mb_strtolower($value));
Why not using [`mb_stripos()`](http://php.net/manual/en/function.mb-stripos.php)?

2018-02-13 10:55 UTC, isisis commented
@Ocramius I'm waiting for this feature as well, what's the current state?

2025-10-26 09:14 UTC, closed without merging