Leverage PSR-4 to provide a shallower tree
doctrine/collections pull request #138
Opened 2018-01-21 19:34 UTC by greg0ire

This should make fuzzy matchers more efficients.

2018-01-21 19:35 UTC, greg0ire commented on phpunit.xml.dist
> +         bootstrap="vendor/autoload.php"
I'm sure this is need it but I'm not sure why. Or rather, I'm not sure why it worked before. It's as if phpunit assumed psr 0

2018-01-21 19:38 UTC, greg0ire commented
If you are ok with this I might do the same on other Doctrine libs.

2018-01-21 23:05 UTC, lcobucci requested changes
Thanks for your effort but the Doctrine team voted against PSR-4 and also decided to not apply the "shallower tree" in any of our projects.

2018-01-21 23:10 UTC, Ocramius commented
Same here: shallow tree is not an advantage to me, and the doctrine
organisation voted against PSR-4 specifically due to the introduced tooling
complexity added by path prefixing.

I'd personally still very much like to keep the path 1:1 with the class
names, as it should be.

PSR-4 as an autoloader is fine and already implemented in this package.

On 22 Jan 2018 00:05, "Luís Cobucci" <notifications@github.com> wrote:

*@lcobucci* requested changes on this pull request.

Thanks for your effort but the Doctrine team voted against PSR-4 and also
decided to not apply the "shallower tree" in any of our projects.
------------------------------

In phpunit.xml.dist
<https://github.com/doctrine/collections/pull/138#discussion_r162828848>:

> @@ -8,16 +8,17 @@
          beStrictAboutOutputDuringTests="true"
          beStrictAboutTestsThatDoNotTestAnything="true"
          beStrictAboutTodoAnnotatedTests="true"
+         bootstrap="vendor/autoload.php"

Not needed when PHPUnit is executed from local composer installation

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/doctrine/collections/pull/138#pullrequestreview-90348231>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/AAJakBJSrw3DUTEaAE2nPfcCvzQmRkhrks5tM8K_gaJpZM4Rl71C>
.

2018-01-22 07:19 UTC, closed without merging

2018-01-22 07:20 UTC, greg0ire commented
Closing then

2021-03-25 23:28 UTC, mvorisek commented
2021 to rethink this?

2021-03-26 07:29 UTC, greg0ire commented
I didn't follow how things evolved, but I noticed that the DBAL does use a shallow tree since 3.0.x so maybe this might be reconsidered indeed.