Enforce no BC breaks against v1.5.0
doctrine/collections pull request #179
Opened 2019-03-24 18:09 UTC by Ocramius

Possibly a good idea for branches in `1.x`, not to be merged into `master`? Just throwing it out there: this would prevent most feedback along the lines of "we can't do that because BC" from human-to-human, which is frustrating.

2019-03-24 18:16 UTC, greg0ire commented
Looks like it cannot be done because the lib requires php 7.2 and this package is supposed to be compatible with 7.1

2019-03-24 18:19 UTC, Ocramius commented
Can bump the PHP version, if needed for `1.7.x`. The idea is that `master` is open for BC breaks, while `1.x` is not.

2019-03-24 18:23 UTC, greg0ire commented
I like the idea! Regarding your first sentence, did you mean `1.6.x` ? Why not bump the php version when releasing `1.6.0`?

2019-04-10 11:26 UTC, Majkl578 requested changes
Bumping library requirement to PHP ^7.2 just to satisfy a dev-dependency sounds like a bit too much IMO. We should seek other solution.

2019-04-10 11:26 UTC, Majkl578 commented on .travis.yml
> +      script: vendor/bin/roave-backward-compatibility-check --from=v1.5.0
Hardcoding tag name here is not a good idea, can we use some kind of wildcard, like _latest 1.x tag_?

2019-04-10 12:06 UTC, ostrolucky commented
I agree with not bumping requirement because of dev dependency

2025-10-24 14:32 UTC, mpdude commented
Is this still relevant, or could this PR be closed?

2025-10-24 14:52 UTC, Ocramius commented
IMO relevant, but the tooling has evolved, and there's no need to specify a base branch anymore, IIRC.

I won't have time to pursue this, but usage via `tools/composer.json` + `tools/composer.lock` is endorsed.

2025-10-26 09:14 UTC, closed without merging