Comparison BIT_AND
doctrine/collections pull request #238
Opened 2020-06-11 18:20 UTC by najved

I was missing a "bit and" comparison for building criteria expression on bit mask fields.

e.g bit mask:

1: imported
2: canceled
4: deleted
8: ...

foo = 5 (1+4)

$expressionBuilder->bitAnd('foo', 1) // true
$expressionBuilder->bitAnd('foo', 5) // true
$expressionBuilder->bitAnd('foo', 2) // false

Implementation and tests included.

2020-06-16 20:06 UTC, SenseException requested changes
Thank you for your PR. Can you please also elaborate which use-case you ran into that made you create this PR?

2020-06-16 20:06 UTC, SenseException commented on tests/Doctrine/Tests/Common/Collections/ExpressionBuilderTest.php
> +        self::assertInstanceOf(Comparison::class, $expr);
The instance check shouldn't be needed in the test. It is a relict for past PHP versions when a return type couldn't be used.

2020-06-16 20:06 UTC, SenseException commented on tests/Doctrine/Tests/Common/Collections/ClosureExpressionVisitorTest.php
> +        self::assertFalse($closure(new TestObject(2)));
Please add a few more false cases like `8` or `11`. Be sure that there are also false-cases with a string-number like in your true-cases.

2020-06-17 19:36 UTC, najved commented
> Thank you for your PR. Can you please also elaborate which use-case you ran into that made you create this PR?

I have a collection of objects with a status field, which can hold different "combined values".

e.g.

```php
class Item {
  const IS_EXPORTED = 1;
  const IS_PAYMENT = 2;
  const IS_CANCELED = 4;

  $status = 3;
  $statusAsArray = [1, 2];
}

$expressionBuilder->bitAnd('status', Item::IS_PAYMENT + Item::IS_CANCELED);
$expressionBuilder->in('statusAsArray', [Item::IS_PAYMENT, Item::IS_CANCELED]) ;
```

"bitAnd" would be similar to "in" and "bitNotAnd" to "notIn".

While writing these lines, i'm not sure if this is just an "edge"-use-case in my legacy code or a good addition for this project :-)

2020-06-21 19:09 UTC, SenseException approved these changes
I don't know about the edge case, but I know that some doctrine/collections classes have a lot of methods which is why I don't know if it makes sense to introduce new ones or if the future of collections will need a different architecture. This needs more reviewers. @doctrine/doctrinecore

2020-06-21 19:24 UTC, morozov commented
Instead performing bitwise operations on a collection, why not have all bits as separate fields? This way, applied to a collection in the DB, the filter could use an index.

2025-10-26 09:14 UTC, closed without merging