Update index.rst
doctrine/collections pull request #254
Opened 2020-09-09 15:27 UTC by ThomasLandauer

* Renaming "count" to "number", since "count" was ambiguous (meaning: how many?)
* Explaining the callback function of `filter()` better

2020-09-09 20:54 UTC, SenseException requested changes
Thank you for the contribution. I agree that `$count` doesn't seem to add to readability, but `$number` neither. The argument of the anonymous function gets every element of the collection injected. What do you think about `$element`, `$item`, `$collectionItem` or `$collectionElement`?

2020-09-09 21:20 UTC, ThomasLandauer commented
Sure! :-)
What I meant: `count` is *ambiguous* - I was first thinking what's injected is the *number of elements* (not the element itself)

2020-09-10 16:56 UTC, SenseException approved these changes

2020-09-10 16:56 UTC, merged

2020-09-10 16:57 UTC, SenseException commented
Thank you @ThomasLandauer