Avoid risky truthy-falsy comparison
doctrine/collections pull request #387
Opened 2024-02-16 21:25 UTC by greg0ire

Stumbled upon this while working on https://github.com/doctrine/collections/pull/386

2024-02-16 22:18 UTC, SenseException requested changes
Is this PR a cosmetic one?

2024-02-16 22:18 UTC, SenseException commented on src/ArrayCollection.php
>              $filtered = array_slice($filtered, (int) $offset, $length, true);
```suggestion
        if ($offset !== null && $offset > 0 || $length !== null && $length > 0) {
            $filtered = array_slice($filtered, $offset, $length, true);
```

2024-02-16 22:39 UTC, greg0ire commented
> Is this PR a cosmetic one?

Sorry, I should have mentioned that it fixes the build by addressing an issue found by Psalm

2024-02-17 12:04 UTC, greg0ire commented
@SenseException after applying your suggestion the tests break like this:

```
1) Doctrine\Tests\Common\Collections\ArrayCollectionTest::testMatchingWithSlicingPreserveKeys with data set "preserve keys on maxresult only" (array(1, 2, 3, 4), array(1, 2), null, 2)
TypeError: array_slice(): Argument #2 ($offset) must be of type int, null given

/home/greg/dev/doctrine-collections/src/ArrayCollection.php:484
/home/greg/dev/doctrine-collections/tests/Common/Collections/BaseArrayCollectionTest.php:356
```

2024-02-17 21:04 UTC, SenseException approved these changes
This is weird because the check in the if block should make it clear that the result should be an integer. `getFirstResult()` can only return null or integer.

2024-02-17 21:33 UTC, merged